### ISSUE TITLE
Try to run the demo and integration tests with Postgress

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx#147]
Currently, the demo/integration tests run against MySQL.
We would like to try against Postgres 

* [x] Allow `postgres` url in [settings](https://github.com/DIRACGrid/diracx/blob/39a73bbd84e8baf96a58d8b7058c2bb0fc1966be/src/diracx/core/settings.py#L24)
* [x] run Postgres in  the helm chart 
* [x] add the missing dependencies (environment.yaml)
* [x] Change the initial [connection string generation](https://github.com/DIRACGrid/diracx-charts/blob/master/diracx/templates/init-secrets/_init-secrets.sh.tpl) in charts

**Comment by ruslan33** [comment]
Hi,

I would like to work on this issue. Can I take it?

**Comment by fstagni** [comment]
This task is "done", even with the comments on if or not we actually make use of PostGres. So, closing.
