### ISSUE TITLE
JobManagerHandler conversion

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/diracx#22]
Continue the implementation of the `/jobs` route.
Missing methods are:

- [ ] getMaxParametricJobs: no need to implement in the router. The legacy adapter should query the CS directly.
- [ ] submitJob(self, jobDesc): started, needs completion (JobParametersDB, JobLoggingDB, etc)
- [ ] confirmBulkSubmission(self, jobIDs) : needs larger discussion about ParametricJobSubmission
- [ ] rescheduleJob(self, jobIDs):  `POST` to `/jobs/{job_id}/reschedule` and `/jobs/reschedule` for bulk
- [ ] removeJob(self, jobIDs): Do we need both `removeJob` and `deleteJob` ?  (If yes, can `removeJob` be a parameter of `deleteJob`)
- [ ] deleteJob(self, jobIDs): see above
- [ ] killJob(self, jobIDs): `POST` to  `/jobs/{job_id}/kill` and `/jobs/kill` for bulk (see [1])
- [ ] resetJob(self, jobIDs): Could this be a parameter to `rescheduleJob`?

[1] We could think of having `killJob` and `rescheduleJob` react to `setStatus(kill)` or `setStatus(reschedule)`. We do not because in general, it is forbidden to set an arbitrary status. `Kill` and `Reschedule` are exceptions, that's why they have a dedicated API.

**Comment by ryuwd** [comment]
In addition to a lot of refactoring: 

-  getMaxParametricJobs: no need to implement in the router. The legacy adapter should query the CS directly.
  - Left this alone (TBD)
- submitJob(self, jobDesc): started, needs completion (JobParametersDB, JobLoggingDB, etc)
  - Left this alone (TBD)
- confirmBulkSubmission(self, jobIDs) : needs larger discussion about ParametricJobSubmission
   - Left this alone (TBD)
- rescheduleJob(self, jobIDs): POST to /jobs/{job_id}/reschedule and /jobs/reschedule for bulk
  - TBD
- removeJob(self, jobIDs): Do we need both removeJob and deleteJob ? (If yes, can removeJob be a parameter of deleteJob)
  - This has become a DELETE operation
- deleteJob(self, jobIDs): see above
  - This has become a DELETE operation
- killJob(self, jobIDs): POST to /jobs/{job_id}/kill and /jobs/kill for bulk (see [1])
  - removed in favour of single job and bulk status change (`PATCH /api/jobs/status`, `PATCH /api/jobs/{job_id/status`)
- resetJob(self, jobIDs): Could this be a parameter to rescheduleJob?
  - TBD with rescheduleJob
